name: aktientool
description: Aktien finden und analysieren wird mit dem Aktientool viel einfacher.  
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  fl_chart: ^0.55.2
  provider: ^6.0.4
  cupertino_icons: ^1.0.5
  url_strategy: ^0.2.0
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

