name: aktientool
description: Aktien finden und analysieren wird mit dem Aktientool viel einfacher.  
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


 
dependencies:
  flutter:
    sdk: flutter
  fl_chart:
    git:
      url: https://github.com/koosoftware/fl_chart
      ref: b4c909c

  cupertino_icons: ^1.0.5
  url_strategy: ^0.2.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  flutter_riverpod: ^2.0.2
  firebase_auth:
  http: ^0.13.5
  dio: ^4.0.6
  font_awesome_flutter:
  google_sign_in:
  google_sign_in_web_redirect:
  shared_preferences:
  url_launcher: ^6.1.6
  webviewx: ^0.2.1
  web_browser: ^0.5.0
  http_auth:
  flutter_svg: ^2.0.0+1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  bs_flutter_selectbox: ^1.3.0
  selectable_list: ^0.1.1
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0
  adaptive_navbar: ^0.0.3
  flutter_paypal: ^0.0.8
  webview_flutter: ^2.1.1
  flutter_icons: ^1.1.0
  carousel_slider: ^4.2.1
  cloud_functions_web: ^4.3.15
  data_table_2: ^2.3.12
  envied: ^0.3.0
  translator: ^0.1.7
  stacked_bar_chart: ^1.0.7+6
  syncfusion_flutter_datagrid: ^20.4.49
  syncfusion_flutter_charts: ^20.4.41


  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  envied_generator: ^0.3.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
