import 'package:flutter/material.dart';

TextStyle kStyleDefault = const TextStyle(
  color: Colors.black,
  fontSize: 16,
  fontWeight: FontWeight.bold,
);

List<String> listLaender = [
  "Alle",
  "USA",
  "Deutschland",
  "Australien",
  "Belgien",
  "Bermuda",
  "China",
  "Dänemark",
  "Finnland",
  "Frankreich",
  "Großbritannien",
  "Hong Kong",
  "Irland",
  "Israel",
  "Italien",
  "Kanada",
  "Luxemburg",
  "Niederlande",
  "Norwegen",
  "Österreich",
  "Schweden",
  "Schweiz",
  "Singapur",
  "Spanien",
  "Japan",
  "Südkorea",
  "Griechenland",
  "Malta",
  "Polen",
  "Portugal",
  "Zypern",
  "Russland",
  "Taiwan",
  "Indien",
  "Neuseeland",
  "Brasilien",
  "Chile",
  "Südafrika",
  "Kaimaninseln",
];

List<String> listSektoren = [
  "Alle",
  "Anlagenbau Zulieferer",
  "Autos/Ersatzteile",
  "Banken",
  "Bau",
  "Baumarkt-Produkte",
  "Biotechnologie",
  "Chemie",
  "Container/Verpackung",
  "Digitales Geld",
  "Einzelhandel gemischt",
  "Einzelhandel spezialisiert",
  "Elektrizität",
  "Elektro-Teile",
  "Energie Dienstleister",
  "Erdöl/Gas",
  "Fonds",
  "Fracht und Logistik",
  "Fracht und Passagiere",
  "Freizeitprodukte",
  "Gas",
  "Gesundheitspflege",
  "Gesundheitspflege Geräte",
  "Getränke",
  "Halbleiter und Zubehör",
  "Handel Nahrung/Medizin",
  "Handelsgesellschaft",
  "Haushalts-/Pflegeprodukte",
  "Haushaltswaren",
  "Holding",
  "Hotels/Unterhaltung",
  "Immobilien",
  "Industriekonglomerate",
  "Industrielle Dienste",
  "Industrielle Lieferanten",
  "Investment Services",
  "Investment Trusts",
  "Kommunikation",
  "Kommunikation Ausrüster",
  "Lebensmittel & Tabak",
  "Maschinen",
  "Maschinen/Zubehör",
  "Medien",
  "Metall/Abbau",
  "Pharmazie",
  "REIT",
  "Raumfahrt/Verteidigung",
  "Smart Contracts",
  "Software/IT Dienste",
  "Technische Konsumgüter",
  "Textil - Kleidung",
  "Transport Infrastruktur",
  "Versicherungen",
  "Versorger",
  "Wasser",
];

class LandWidget {
  const LandWidget(this.name);
  final String name;
}

late List<LandWidget> _land = <LandWidget>[
  LandWidget("Alle"),
  LandWidget("USA"),
  LandWidget("Deutschland"),
  LandWidget("Australien"),
  LandWidget("Belgien"),
  LandWidget("Bermuda"),
  LandWidget("China"),
  LandWidget("Dänemark"),
  LandWidget("Finnland"),
  LandWidget("Frankreich"),
  LandWidget("Großbritanien"),
  LandWidget("Hong-Kong"),
  LandWidget("Irland"),
  LandWidget("Israel"),
  LandWidget("Italien"),
  LandWidget("Kanada"),
  LandWidget("Luxemburg"),
  LandWidget("Niederlande"),
  LandWidget("Norwegen"),
  LandWidget("Österreich"),
  LandWidget("Schweden"),
  LandWidget("Schweiz"),
  LandWidget("Singapur"),
  LandWidget("Spanien"),
  LandWidget("Japan"),
  LandWidget("Südkorea"),
  LandWidget("Griechenland"),
  LandWidget("Malta"),
  LandWidget("Polen"),
  LandWidget("Portugal"),
  LandWidget("Zypern"),
  LandWidget("Russland"),
  LandWidget("Taiwan"),
  LandWidget("Indien"),
  LandWidget("Neuseeland"),
  LandWidget("Brasilien"),
  LandWidget("Chile"),
  LandWidget("Südafrika"),
  LandWidget("Kaimaninseln"),
];
