import 'package:intl/intl.dart';

class DCFLeveredModel {
  int year;
  double revenue;
  double revenuePercentage;
  double operatingCashFlow;
  double operatingCashFlowPercentage;
  double capitalExpenditure;
  double capitalExpenditurePercentage;
  double price;
  double beta;
  double dilutedSharesOutstanding;
  double costofDebt;
  double taxRate;
  double afterTaxCostOfDebt;
  double riskFreeRate;
  double marketRiskPremium;
  double costOfEquity;
  double totalDebt;
  double totalEquity;
  double totalCapital;
  double debtWeighting;
  double equityWeighting;
  double wacc;
  double pvLfcf;
  double sumPvLfcf;
  double longTermGrowthRate;
  double freeCashFlow;
  double terminalValue;
  double presentTerminalValue;
  double enterpriseValue;
  double netDebt;
  double equityValue;
  double equityValuePerShare;
  double freeCashFlowT1;

  DCFLeveredModel(
      {required this.year,
      required this.revenue,
      required this.revenuePercentage,
      required this.capitalExpenditure,
      required this.capitalExpenditurePercentage,
      required this.price,
      required this.beta,
      required this.dilutedSharesOutstanding,
      required this.costofDebt,
      required this.taxRate,
      required this.afterTaxCostOfDebt,
      required this.riskFreeRate,
      required this.marketRiskPremium,
      required this.costOfEquity,
      required this.totalDebt,
      required this.totalEquity,
      required this.totalCapital,
      required this.debtWeighting,
      required this.equityWeighting,
      required this.wacc,
      required this.operatingCashFlow,
      required this.pvLfcf,
      required this.sumPvLfcf,
      required this.longTermGrowthRate,
      required this.freeCashFlow,
      required this.terminalValue,
      required this.presentTerminalValue,
      required this.enterpriseValue,
      required this.netDebt,
      required this.equityValue,
      required this.equityValuePerShare,
      required this.freeCashFlowT1,
      required this.operatingCashFlowPercentage});

  factory DCFLeveredModel.fromJson(Map<String, dynamic> json) =>
      DCFLeveredModel(
          year: int.parse(json['year']),
          revenue: json['revenue'],
          revenuePercentage: json['revenuePercentage'],
          capitalExpenditure: json['capitalExpenditure'],
          capitalExpenditurePercentage: json['capitalExpenditurePercentage'],
          price: json['price'],
          beta: json['beta'],
          dilutedSharesOutstanding: json['dilutedSharesOutstanding'],
          costofDebt: json['costofDebt'],
          taxRate: json['taxRate'],
          afterTaxCostOfDebt: json['afterTaxCostOfDebt'],
          riskFreeRate: json['riskFreeRate'],
          marketRiskPremium: json['marketRiskPremium'],
          costOfEquity: json['costOfEquity'],
          totalDebt: json['totalDebt'],
          totalEquity: json['totalEquity'],
          totalCapital: json['totalCapital'],
          debtWeighting: json['debtWeighting'],
          equityWeighting: json['equityWeighting'],
          wacc: json['wacc'],
          operatingCashFlow: json['operatingCashFlow'],
          pvLfcf: json['pvLfcf'],
          sumPvLfcf: json['sumPvLfcf'],
          longTermGrowthRate: json['longTermGrowthRate'],
          freeCashFlow: json['freeCashFlow'],
          terminalValue: json['terminalValue'],
          presentTerminalValue: json['presentTerminalValue'],
          enterpriseValue: json['enterpriseValue'],
          netDebt: json['netDebt'],
          equityValue: json['equityValue'],
          equityValuePerShare: json['equityValuePerShare'],
          freeCashFlowT1: json['freeCashFlowT1'],
          operatingCashFlowPercentage: json['operatingCashFlowPercentage']);
}
